version: "3"

services:
  web:
    container_name: web_nuxt
    build: .
    volumes: 
      - .:/web
      - ./node_modules:/web/node_modules
    ports: 
      - "5000:5000"
    environment: 
      HOST: 0.0.0.0
